'use client';

import { useState, useRef, useMemo, useEffect } from 'react';
import { streamAiChat } from '@/lib/ai-stream';
import type { CheckItem } from './self-check-panel';
import { StoryEditor } from '@/components/editor/story-editor';

export interface ModifyItem {
  id: string;
  beforeText: string;
  afterText: string;
  status: 'pending' | 'accepted' | 'skipped' | 'rewriting';
  reason?: string;
  rewriteContent?: string;
}

interface ModifyPanelProps {
  /** 当前章节正文（纯文本） */
  chapterContent: string;
  /** 自检条目（含修改原因、原文、修改后） */
  selfCheckItems: CheckItem[];
  /** 自检报告原文（当 items 为空时的 fallback） */
  rawReport?: string;
  /** AI 模型配置 ID */
  configId: string;
  /** 项目 ID */
  projectId: string;
  /** 是否自动触发修改生成 */
  autoGenerate?: boolean;
  /** 修改应用后的回调：完整修改后内容(纯文本)、所有被修改的文本片段列表 */
  onModificationsApplied: (modifiedContent: string, modifiedTexts: string[]) => void;
  /** 跳转到定稿步骤 */
  onNavigateToFinalize: () => void;
  /** 是否显示正文编辑器 */
  showEditor?: boolean;
  /** 编辑器内容（已修改的正文HTML） */
  editorContent?: string;
  /** 编辑器内容变更回调 */
  onEditorChange?: (content: string) => void;
  /** 重新生成时的回调 */
  onRetry?: () => void;
  /** 保存修改结果到持久化 */
  onSaveModificationResult?: (content: string, summary: string) => void;
}

// 检查项类型中文映射
const TYPE_LABELS: Record<string, { label: string; color: string }> = {
  consistency: { label: '一致性', color: 'bg-blue-100 text-blue-700' },
  character: { label: '人物', color: 'bg-purple-100 text-purple-700' },
  setting: { label: '设定', color: 'bg-green-100 text-green-700' },
  logic: { label: '逻辑', color: 'bg-orange-100 text-orange-700' },
  pacing: { label: '节奏', color: 'bg-pink-100 text-pink-700' },
  quality: { label: '文笔', color: 'bg-indigo-100 text-indigo-700' },
};

function extractSuggestions(items: CheckItem[]): string {
  return items
    .map((item, i) => `${i + 1}. 【${item.reason}】\n   原文：${item.original}\n   建议：${item.suggestion}`)
    .join('\n\n');
}

export function ModifyPanel({
  chapterContent, selfCheckItems, rawReport, configId, projectId,
  onModificationsApplied, onNavigateToFinalize,
  autoGenerate, showEditor, editorContent, onEditorChange, onRetry,
  onSaveModificationResult,
}: ModifyPanelProps) {
  const [phase, setPhase] = useState<'prepare' | 'generating' | 'review' | 'applied'>('prepare');
  const [generatingText, setGeneratingText] = useState('');
  const [fullModifiedContent, setFullModifiedContent] = useState('');
  const [modifications, setModifications] = useState<ModifyItem[]>([]);
  const [modifiedTexts, setModifiedTexts] = useState<string[]>([]);

  const abortRef = useRef(false);
  const hasAutoGenerated = useRef(false);

  // 自动触发修改生成（仅首次渲染）
  useEffect(() => {
    if (autoGenerate && phase === 'prepare' && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleGenerateModifications();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase, autoGenerate]);

  // 构建 AI 提示词
  const suggestions = useMemo(() => {
    if (selfCheckItems.length > 0) return extractSuggestions(selfCheckItems);
    if (rawReport) return rawReport;
    return '';
  }, [selfCheckItems, rawReport]);

  const handleGenerateModifications = async () => {
    if (!suggestions.trim() || !configId) return;

    const plainContent = chapterContent.replace(/<[^>]*>/g, '').slice(0, 15000);

    const prompt = `你是一名专业文学编辑。请根据以下自检报告中的修改建议，对小说正文进行精准修改。

【修改约束】
1. 针对每条修改建议逐一处理，必须输出多条修改明细（与建议数对应）
2. 只根据修改意见修改，不要重写或大幅改动无关段落
3. 保持原文的文风、人物性格和叙事节奏
4. 修改要精准，不要过度发挥
5. 修改前的原文片段必须与正文完全一致，可直接用于查找替换

【当前章节正文】
${plainContent}

【自检修改建议】
${suggestions}

请严格按以下格式输出（只输出修改明细，不要输出修改后全文）：

1.【位置/原因】
修改前：[原文片段，必须与正文完全一致]
修改后：[修改后片段]

2.【位置/原因】
修改前：[原文片段，必须与正文完全一致]
修改后：[修改后片段]

（以此类推，有多少条修改建议就输出多少条明细）`;

    setPhase('generating');
    setGeneratingText('');
    setFullModifiedContent('');
    setModifications([]);
    abortRef.current = false;

    const systemMsg = { role: 'system' as const, content: '你是一名资深文学编辑，擅长根据自检报告的建议对小说正文进行精准修改。请严格按格式输出。' };
    const userMsg = { role: 'user' as const, content: prompt };

    let fullResult = '';

    try {
      for await (const chunk of streamAiChat({
        configId,
        messages: [systemMsg, userMsg],
        projectId,
      })) {
        if (abortRef.current) break;
        if (chunk.error) {
          setGeneratingText(`修改出错：${chunk.error}`);
          return;
        }
        if (chunk.content) {
          fullResult += chunk.content;
          setGeneratingText(fullResult);
        }
      }
    } catch {
      setGeneratingText('修改失败，请检查网络连接');
      return;
    }

    if (!fullResult) {
      setGeneratingText('AI 未返回修改结果');
      return;
    }

    const parsed = parseModificationResult(fullResult, plainContent);
    setFullModifiedContent(parsed.fullContent);
    setModifications(parsed.modifications);
    setPhase('review');
  };

  const handleStopGenerating = () => {
    abortRef.current = true;
  };

  const handleItemStatus = (id: string, status: ModifyItem['status'], rewriteContent?: string) => {
    setModifications(prev => prev.map(m =>
      m.id === id ? {
        ...m,
        status,
        rewriteContent,
        ...(status === 'accepted' && rewriteContent ? { afterText: rewriteContent } : {}),
      } : m
    ));
  };

  const handleApplyModifications = () => {
    const finalMods = modifications.map(m => ({
      ...m,
      status: m.status === 'pending' ? 'accepted' as const : m.status,
    }));
    setModifications(finalMods);

    // 从原文纯文本出发，逐条应用修改并用 Unicode 标记包裹修改后文本
    let finalContent = chapterContent.replace(/<[^>]*>/g, '').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"');
    for (const item of finalMods) {
      if (item.status === 'accepted' && item.beforeText && item.afterText) {
        finalContent = finalContent.replace(item.beforeText, `\uE000${item.afterText}\uE001`);
      }
      // skipped: 保持原文不替换
    }

    setModifiedTexts([]);
    setPhase('applied');
    onModificationsApplied(finalContent, []);
    // 持久化修改结果（去掉标记）
    const cleanContent = finalContent.replace(/\uE000/g, '').replace(/\uE001/g, '');
    onSaveModificationResult?.(cleanContent, `共 ${modifications.length} 条修改建议，${finalMods.filter(m => m.status === 'accepted').length} 处已替换`);
  };

  const handleRetry = () => {
    setPhase('prepare');
    setGeneratingText('');
    setFullModifiedContent('');
    setModifications([]);
    setModifiedTexts([]);
    hasAutoGenerated.current = false;
    onRetry?.();
  };

  // ─── 生成阶段 ──────────────────────────────────────────
  if (phase === 'generating') {
    return (
      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <h2 className="font-semibold mb-4">AI 正在根据自检建议生成修改...</h2>
        <div className="space-y-3">
          {!generatingText ? (
            <div className="flex items-center gap-3 py-4">
              <div className="w-5 h-5 border-2 border-gray-900 border-t-transparent rounded-full animate-spin" />
              <p className="text-sm text-amber-600">AI 正在分析修改，thinking模型需要一点时间，请耐心等待</p>
            </div>
          ) : (
            <>
              <p className="text-xs text-gray-400">AI 正在生成修改方案...</p>
              <pre className="whitespace-pre-wrap text-xs text-gray-700 bg-gray-50 rounded-lg p-3 max-h-64 overflow-y-auto border border-gray-100">
                {generatingText}
              </pre>
            </>
          )}
          <button onClick={handleStopGenerating}
            className="px-4 py-1.5 border border-gray-300 rounded-lg text-xs font-medium hover:bg-gray-50 transition">
            停止生成
          </button>
        </div>
      </div>
    );
  }

  // ─── 已应用阶段 ─────────────────────────────────────────
  if (phase === 'applied') {
    return (
      <div className="bg-white rounded-xl border border-gray-200 flex flex-col min-h-0" style={{ minHeight: 'calc(100vh - 260px)' }}>
        <div className="p-4 border-b border-gray-100">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="text-green-600 text-lg">✓</div>
              <div>
                <h2 className="font-semibold text-sm">修改已全部应用</h2>
                <p className="text-xs text-gray-400">
                  共 {modifications.length} 条建议，{modifiedTexts.length} 处已替换
                </p>
              </div>
            </div>
            <button onClick={onNavigateToFinalize}
              className="px-4 py-1.5 bg-amber-500 text-white rounded-lg text-xs font-medium hover:bg-amber-600 transition">
              确认定稿 →
            </button>
          </div>
        </div>

        {modifications.length > 0 && (
          <div className="border-b border-gray-100">
            <div className="max-h-48 overflow-y-auto p-4 space-y-1.5">
              {modifications.map((item, i) => (
                <div key={item.id} className="flex items-start gap-3 text-xs p-2 rounded-lg border border-gray-100 bg-gray-50/50">
                  <span className="text-gray-400 w-5 shrink-0 mt-0.5">#{i + 1}</span>
                  <div className="flex-1 min-w-0">
                    {item.reason && <p className="font-medium text-gray-700 truncate">{item.reason}</p>}
                    <div className="mt-1 flex gap-2">
                      {item.beforeText && <span className="line-through text-gray-400 truncate block flex-1">{item.beforeText}</span>}
                      {item.afterText && <span className="text-green-700 truncate block flex-1">{item.afterText}</span>}
                    </div>
                  </div>
                  <span className={`shrink-0 px-1.5 py-0.5 text-xs rounded ${
                    item.status === 'accepted' ? 'bg-green-100 text-green-700' :
                    item.status === 'skipped' ? 'bg-gray-100 text-gray-500' :
                    'bg-yellow-100 text-yellow-600'
                  }`}>
                    {item.status === 'accepted' ? '已通过' :
                     item.status === 'skipped' ? '已跳过' : '待审核'}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {showEditor && onEditorChange && (
          <div className="flex-1 flex flex-col min-h-0 p-4 pt-3">
            <h3 className="text-xs font-medium text-gray-500 mb-2">修改后正文（可继续编辑）</h3>
            <div className="flex-1 border border-gray-200 rounded-lg overflow-hidden">
              <StoryEditor
                content={editorContent || ''}
                onChange={onEditorChange}
                placeholder="修改后的正文..."
                editable={true}
              />
            </div>
          </div>
        )}
      </div>
    );
  }

  // ─── 准备阶段 ────────────────────────────────────────────
  if (phase === 'prepare') {
    return (
      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <h2 className="font-semibold mb-4">AI 修改</h2>
        <div className="space-y-3">
          <div className="bg-gray-50 rounded-lg p-4 border border-gray-100">
            <p className="text-xs text-gray-400 mb-2">
              已导入自检建议，AI 将根据以下内容生成修改条目：
            </p>
            <pre className="whitespace-pre-wrap text-sm text-gray-700 max-h-40 overflow-y-auto">
              {suggestions || '（无修改建议）'}
            </pre>
          </div>
          <p className="text-xs text-gray-400">
            {selfCheckItems.length > 0
              ? `共 ${selfCheckItems.length} 条建议，AI 将逐一生成具体的修改条目，你可逐条确认、手动编辑或要求重写。`
              : 'AI 将根据自检报告生成修改条目，你可逐条确认、手动编辑或要求重写。'}
          </p>
          <button onClick={handleGenerateModifications}
            disabled={!suggestions.trim() || !configId}
            className="w-full py-2.5 bg-gray-900 text-white rounded-lg text-sm font-medium hover:bg-gray-800 transition disabled:opacity-50">
            生成修改条目
          </button>
        </div>
      </div>
    );
  }

  // ─── 审核阶段 ────────────────────────────────────────────
  const acceptedCount = modifications.filter(m => m.status === 'accepted').length;
  const skippedCount = modifications.filter(m => m.status === 'skipped').length;
  const pendingCount = modifications.filter(m => m.status === 'pending').length;
  return (
    <div className="bg-white rounded-xl border border-gray-200 p-6">
      <div className="flex items-center justify-between mb-2">
        <h2 className="font-semibold">AI 修改 — 审核修改条目</h2>
        <div className="flex items-center gap-3 text-xs text-gray-400">
          <span className="text-green-600">通过 {acceptedCount}</span>
          <span className="text-gray-400">跳过 {skippedCount}</span>
          <span className="text-yellow-600">待审 {pendingCount}</span>
        </div>
      </div>
      {/* 审核提示 */}
      <div className="text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded-lg p-3 mb-4">
        建议审核每条修改内容，您可以要求重写或手动编辑
      </div>

      {modifications.length > 0 ? (
        <div className="space-y-3 max-h-[480px] overflow-y-auto pr-1">
          {modifications.map((item, i) => (
            <ModificationCard
              key={item.id}
              index={i + 1}
              item={item}
              onStatusChange={(status, rewrite) => handleItemStatus(item.id, status, rewrite)}
            />
          ))}
        </div>
      ) : (
        <div className="text-center py-4">
          <p className="text-sm text-gray-500">AI 未解析到具体的修改明细。</p>
          <p className="text-xs text-gray-400 mt-1">你可以尝试重新生成。</p>
        </div>
      )}

      <div className="flex gap-2 mt-4 pt-3 border-t border-gray-100">
        <button onClick={handleRetry}
          className="flex-1 py-2 border border-gray-300 rounded-lg text-sm font-medium hover:bg-gray-50 transition">
          重新生成
        </button>
        {modifications.length > 0 && (
          <button onClick={handleApplyModifications}
            className="flex-1 py-2 bg-green-600 text-white rounded-lg text-sm font-medium hover:bg-green-700 transition">
            通过全部修改并应用
          </button>
        )}
      </div>
    </div>
  );
}

// ─── 修改对比卡片 ──────────────────────────────────────────
function ModificationCard({ index, item, onStatusChange }: {
  index: number;
  item: ModifyItem;
  onStatusChange: (status: ModifyItem['status'], rewriteContent?: string) => void;
}) {
  const [editing, setEditing] = useState(false);
  const [editBefore, setEditBefore] = useState(item.beforeText);
  const [editAfter, setEditAfter] = useState(item.afterText);

  const handleEditSave = () => {
    onStatusChange('accepted', editAfter);
    setEditing(false);
  };

  if (item.status === 'accepted' && item.rewriteContent) {
    return (
      <div className="border border-gray-200 rounded-lg overflow-hidden">
        <div className="px-3 py-2 bg-green-50 border-b border-green-100 flex items-center justify-between">
          <span className="text-xs font-medium text-green-700">修改 #{index}：{item.reason}</span>
          <span className="px-1.5 py-0.5 text-xs rounded bg-green-100 text-green-700">已编辑通过</span>
        </div>
        {editing ? (
          <div className="p-3 space-y-2">
            <div>
              <p className="text-xs text-red-400 font-medium mb-1">原文（可编辑）</p>
              <textarea
                value={editBefore}
                onChange={e => setEditBefore(e.target.value)}
                className="w-full h-16 p-2 text-xs bg-red-50 border border-red-200 rounded resize-none focus:outline-none focus:ring-1 focus:ring-gray-400"
              />
            </div>
            <div>
              <p className="text-xs text-green-600 font-medium mb-1">修改后（可编辑）</p>
              <textarea
                value={editAfter}
                onChange={e => setEditAfter(e.target.value)}
                className="w-full h-16 p-2 text-xs bg-green-50 border border-green-200 rounded resize-none focus:outline-none focus:ring-1 focus:ring-gray-400"
              />
            </div>
            <div className="flex gap-2">
              <button onClick={() => setEditing(false)}
                className="px-3 py-1 border border-gray-300 rounded text-xs font-medium hover:bg-gray-50">
                取消
              </button>
              <button onClick={handleEditSave}
                className="px-3 py-1 bg-green-600 text-white rounded text-xs font-medium hover:bg-green-700">
                保存编辑
              </button>
            </div>
          </div>
        ) : (
          <>
            <div className="p-3">
              <p className="text-xs text-green-600 mb-1">编辑后内容：</p>
              <pre className="whitespace-pre-wrap text-xs text-gray-700">{item.afterText}</pre>
            </div>
            <div className="px-3 py-2 border-t border-gray-100">
              <button onClick={() => { setEditAfter(item.afterText); setEditing(true); }}
                className="px-3 py-1.5 border border-gray-300 rounded text-xs font-medium hover:bg-gray-50 transition">
                重新编辑
              </button>
            </div>
          </>
        )}
      </div>
    );
  }

  return (
    <div className="border border-gray-200 rounded-lg overflow-hidden">
      <div className="px-3 py-2 bg-gray-50 border-b border-gray-100 flex items-center justify-between">
        <span className="text-xs font-medium text-gray-600">
          修改 #{index}{item.reason ? `：${item.reason}` : ''}
        </span>
        <span className={`px-1.5 py-0.5 text-xs rounded ${
          item.status === 'accepted' ? 'bg-green-100 text-green-700' :
          item.status === 'skipped' ? 'bg-gray-100 text-gray-500' :
          'bg-yellow-100 text-yellow-600'
        }`}>
          {item.status === 'accepted' ? '已通过' :
           item.status === 'skipped' ? '已跳过' : '待审核'}
        </span>
      </div>

      <div className="p-3 space-y-2">
        {editing ? (
          <>
            <div>
              <p className="text-xs text-red-400 font-medium mb-1">原文（可编辑）</p>
              <textarea
                value={editBefore}
                onChange={e => setEditBefore(e.target.value)}
                className="w-full h-16 p-2 text-xs bg-red-50 border border-red-200 rounded resize-none focus:outline-none focus:ring-1 focus:ring-gray-400"
              />
            </div>
            <div>
              <p className="text-xs text-green-600 font-medium mb-1">修改后（可编辑）</p>
              <textarea
                value={editAfter}
                onChange={e => setEditAfter(e.target.value)}
                className="w-full h-16 p-2 text-xs bg-green-50 border border-green-200 rounded resize-none focus:outline-none focus:ring-1 focus:ring-gray-400"
              />
            </div>
            <div className="flex gap-2">
              <button onClick={() => { setEditing(false); setEditBefore(item.beforeText); setEditAfter(item.afterText); }}
                className="px-3 py-1 border border-gray-300 rounded text-xs font-medium hover:bg-gray-50">
                取消
              </button>
              <button onClick={handleEditSave}
                className="px-3 py-1 bg-green-600 text-white rounded text-xs font-medium hover:bg-green-700">
                保存编辑
              </button>
            </div>
          </>
        ) : (
          <>
            <div className="bg-red-50 border border-red-100 rounded p-2">
              <p className="text-xs text-red-500 mb-1">修改前</p>
              <pre className="whitespace-pre-wrap text-xs text-gray-700">{item.beforeText}</pre>
            </div>
            <div className="bg-green-50 border border-green-100 rounded p-2">
              <p className="text-xs text-green-600 mb-1">修改后</p>
              <pre className="whitespace-pre-wrap text-xs text-gray-700">{item.afterText}</pre>
            </div>
          </>
        )}
      </div>

      {item.status === 'pending' && !editing && (
        <div className="px-3 py-2 border-t border-gray-100 flex gap-2 flex-wrap">
          <button onClick={() => onStatusChange('skipped')}
            className="flex-1 min-w-[80px] py-1.5 border border-gray-300 rounded text-xs font-medium hover:bg-gray-50 transition">
            跳过
          </button>
          <button onClick={() => setEditing(true)}
            className="flex-1 min-w-[80px] py-1.5 border border-gray-400 text-gray-600 rounded text-xs font-medium hover:bg-gray-50 transition">
            手动编辑
          </button>
          <button onClick={() => onStatusChange('accepted')}
            className="flex-1 min-w-[80px] py-1.5 bg-green-600 text-white rounded text-xs font-medium hover:bg-green-700 transition">
            通过
          </button>
        </div>
      )}

      {(item.status === 'accepted' || item.status === 'skipped') && !editing && (
        <div className="px-3 py-2 border-t border-gray-100">
          <button onClick={() => setEditing(true)}
            className="px-3 py-1.5 border border-gray-300 rounded text-xs font-medium hover:bg-gray-50 transition">
            重新编辑
          </button>
        </div>
      )}
    </div>
  );
}

// ─── 解析 AI 返回的修改结果 ──────────────────────────────
function parseModificationResult(
  fullText: string,
  originalContent: string
): { fullContent: string; modifications: ModifyItem[] } {
  const modifications: ModifyItem[] = [];

  // 去掉可能的 markdown 标题行
  const detailText = fullText.replace(/^##\s*.*$/gm, '').trim();

  if (detailText) {
    // 主正则：支持 【】、[]、或纯文字标题
    const itemRegex = /\d+\.\s*(?:【|\[)?(.+?)(?:】|\])?\s*\n([\s\S]*?)(?=\n(?:\d+\.\s*(?:【|\[)|$))/g;
    let match;
    while ((match = itemRegex.exec(detailText)) !== null) {
      const reason = match[1].trim();
      const body = match[2].trim();
      const beforeMatch = body.match(/修改前[：:]([\s\S]*?)(?=修改后[：:])/);
      const afterMatch = body.match(/修改后[：:]([\s\S]*)/);
      const beforeText = beforeMatch ? beforeMatch[1].trim() : '';
      const afterText = afterMatch ? afterMatch[1].trim() : '';

      if (beforeText || afterText) {
        modifications.push({
          id: `mod-${modifications.length + 1}-${Date.now()}`,
          reason,
          beforeText,
          afterText,
          status: 'pending',
        });
      }
    }

    // fallback 逐行解析
    if (modifications.length === 0) {
      const lines = detailText.split('\n');
      let currentItem: { reason: string; beforeParts: string[]; afterParts: string[]; mode: string | null } | null = null;

      for (const line of lines) {
        const itemHeader = line.match(/\d+\.\s*(.*)/);
        if (itemHeader) {
          if (currentItem && (currentItem.beforeParts.length > 0 || currentItem.afterParts.length > 0)) {
            modifications.push({
              id: `mod-${modifications.length + 1}-${Date.now()}`,
              reason: currentItem.reason,
              beforeText: currentItem.beforeParts.join('\n').trim(),
              afterText: currentItem.afterParts.join('\n').trim(),
              status: 'pending',
            });
          }
          currentItem = {
            reason: itemHeader[1].trim().replace(/^[【\[(]|[】\])]$/g, ''),
            beforeParts: [], afterParts: [], mode: null,
          };
        } else if (currentItem) {
          const bl = line.match(/修改前[：:]\s*(.*)/);
          const al = line.match(/修改后[：:]\s*(.*)/);
          if (bl) { currentItem.mode = 'before'; currentItem.beforeParts.push(bl[1]); }
          else if (al) { currentItem.mode = 'after'; currentItem.afterParts.push(al[1]); }
          else if (currentItem.mode === 'before') currentItem.beforeParts.push(line);
          else if (currentItem.mode === 'after') currentItem.afterParts.push(line);
        }
      }
      if (currentItem && (currentItem.beforeParts.length > 0 || currentItem.afterParts.length > 0)) {
        modifications.push({
          id: `mod-${modifications.length + 1}-${Date.now()}`,
          reason: currentItem.reason,
          beforeText: currentItem.beforeParts.join('\n').trim(),
          afterText: currentItem.afterParts.join('\n').trim(),
          status: 'pending',
        });
      }
    }
  }

  // 从原文逐条替换生成全文
  let fullContent = originalContent;
  for (const mod of modifications) {
    if (mod.beforeText && mod.afterText) {
      fullContent = fullContent.replace(mod.beforeText, mod.afterText);
    }
  }

  return { fullContent, modifications };
}
